### ISSUE TITLE
PC/SPのデザインを更新

### ISSUE THREAD

**Issue by mikkame** [codeforjapan/mapprint-nuxt#5]
SPのデザインはタイミング悪くデグレです。
申し訳ないのですが再度対応おねがいします

参考：

https://github.com/codeforjapan/mapprint/issues/192
https://github.com/codeforjapan/mapprint/issues/199

**Comment by kaizumaki** [comment]
了解しました！対応します。

**Comment by kaizumaki** [comment]
こちらのissueを分割しました。
codeforjapan/mapprint#199

@fujirio75 @forestgrovetrees @halsk @bptaku

**Comment by halsk** [comment]
@kaizumaki @mikkame  このissueって、一旦クローズしても大丈夫ですか？

**Comment by halsk** [comment]
ああ、そうか。すみません。これまでのデザインを適用するチケットかと思ってました。
デザインの話はしたいのですが、別チケット立てたほうが良いと思うので、一旦クローズしますね。
