### ISSUE TITLE
凡例を表示する

### ISSUE THREAD

**Issue by mikkame** [codeforjapan/mapprint-nuxt#6]
すみません、未実装です。

お手伝いいただきたく思います

**Comment by kaizumaki** [comment]
私もまだ現状で未実装です。
https://github.com/codeforjapan/mapprint/issues/191

二度手間になるので、こちらのnuxt版で実装するということでいいでしょうか？

**Comment by mikkame** [comment]
はい、多分その方向で大丈夫です。
@kaizumaki さんにアサインしてもよろしいでしょうか？

**Comment by kaizumaki** [comment]
もちろんです！アサインしてください。
